sudo: required
services:
  - docker

before_install:
  - docker build -t babblegrabble/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true babblegrabble/react-test npm test

after_success:
  - docker build -t babblegrabble/multi-client ./client
  - docker build -t babblegrabble/multi-nginx ./nginx
  - docker build -t babblegrabble/multi-server ./server
  - docker build -t babblegrabble/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push babblegrabble/multi-client
  - docker push babblegrabble/multi-nginx
  - docker push babblegrabble/multi-server
  - docker push babblegrabble/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-872187735736"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY